name: variable-test

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  TEST_RUN: ${{ secrets.TEST_RUN }}
  NAME: Chris
  
jobs:
  variable-true:
    runs-on: ubuntu-latest
#     if: TEST_RUN == "true"
    steps:
      - name: Run Test
        run: |
          echo "Running Test"
          echo $NAME
          
  variable-false:
   runs-on: ubuntu-latest
#    if: TEST_RUN == "false"
   steps:
     - name: Skip Test
       run: |
        echo "Skipping Test"
