name: variable-test

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
      
env:
  TEST_RUN: ${{secrets.TEST_RUN}}
  
jobs:
  variable-true:
    if: TEST_RUN == true
    runs-on: ubuntu-latest
    steps:
      - name: Run Test
        run: |
          echo "Running Test"
          
  variable-false:
   if: TEST_RUN == false
   runs-on: ubuntu-latest
   steps:
     - name: Skip Test
       run: |
        echo "Skipping Test"
